# Generated by Django 3.2.3 on 2021-06-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourafricablog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
