# Generated by Django 3.2.3 on 2021-05-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourafricablog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
