# Generated by Django 3.2.3 on 2021-06-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourafricablog', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=100, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
