# Generated by Django 3.2.3 on 2021-05-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourafricablog', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
