# Generated by Django 3.2.3 on 2021-05-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourafricablog', '0004_alter_blog_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
