# Generated by Django 3.2.3 on 2021-05-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourafricablog', '0007_alter_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
