# Generated by Django 3.2 on 2021-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1024)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('report', models.CharField(blank=True, max_length=1024)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
