# Generated by Django 3.2 on 2021-04-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210427_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=30)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_subject', models.CharField(max_length=30)),
                ('your_message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='Github',
            field=models.CharField(max_length=35),
        ),
    ]
